In [1]:
import numpy as np

v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
escalar = 2

# 1. Multiplicación elemento a elemento
prod_elementos = v1 * v2  # Resultado: [ 4 10 18]

# 2. Producto escalar (dot product) - Resultado un solo número
prod_escalar = np.dot(v1, v2)  # 1*4 + 2*5 + 3*6 = 32
prod_escalar_alternativo = v1 @ v2  # Uso del operador @

# 3. Multiplicación de vector por escalar
prod_vector_escalar = v1 * escalar  # Resultado: [2 4 6]

In [2]:
v1 = np.array([0.5, 0.5, 0.5])
v1

array([0.5, 0.5, 0.5])

In [ ]:
qvtqv= np.dot(v1.T,v1)
qvtqv

()

In [56]:
qv = np.array([[0.5, 0.5, 0.5]]).T#reshape(-1, 1)
print(qv.shape)
print(qv)

(3, 1)
[[0.5]
 [0.5]
 [0.5]]


In [21]:
qvt = qv.T
qvt

array([[0.5, 0.5, 0.5]])

In [22]:
qvtqv = np.dot(qvt,qv)
qvtqv

array([[0.75]])

In [57]:
v = np.array([0,0,1]).reshape(-1,1)
v#.shape

array([[0],
       [0],
       [1]])

In [27]:
qvtV = np.dot(qvt, v)
qvtV

array([[0.5]])

In [38]:
twoqvdot = np.dot(2,np.dot(qv,qvtV))
twoqvdot
#twoqvdot.shape

array([[0.5],
       [0.5],
       [0.5]])

In [60]:
qvtXv = np.cross(qv.ravel(), v.ravel()).reshape(3, 1)
qvtXv

array([[ 0.5],
       [-0.5],
       [ 0. ]])